name: docs
'on':
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone Boost super-project
        run: git clone --recursive --jobs 8 https://github.com/boostorg/boost.git
      - name: Switching to master branch
        working-directory: boost/
        run: git checkout master
      - name: Updating master branch
        working-directory: boost/
        run: |
          git checkout master
          git pull
          git submodule update --init --recursive --jobs 8
      - name: Switching to uBlas & Adding and Updating my fork
        working-directory: boost/
        run: |
          cd libs/numeric/ublas
          git remote add fork https://github.com/shikharvashistha/ublas.git
          git fetch fork
      - name: Switching to feature/doc
        working-directory: boost/libs/numeric/ublas
        run: |
          git fetch
          git checkout feature/doc
      - name: Building B2 engine
        run: |
          git clone https://github.com/boostorg/build.git
          cd build
          ./bootstrap.sh
          ./b2 install --prefix=../boost/libs/numeric/ublas/doc
      - name: Building docs
        working-directory: boost/libs/numeric/ublas/doc/bin
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install asciidoctor
          ./b2 -j 8 --toolset=gcc ../
